services:
  school-db:
    image: postgres:15-alpine
    container_name: school-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school_db
    volumes:
      - postgres-school-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  school-app:
    build:
      dockerfile: Dockerfile
    container_name: school-app
    ports:
      - "8080:8080"
    depends_on:
      school-db:
        condition: service_healthy
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=school_db
      - DB_PORT=5432
      - DB_HOST=school-db
      - PORT=8080
    env_file:
      - .env
    volumes:
      - ~/go/pkg/mod:/go/pkg/mod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-school-data:
    driver: local
